
    
    /**/
    export enum UnitedStates {
       al = "Alabama",
        ak = "Alaska",
        ar = "Arkansas",
        az = "Arizona",
        ca = "California",
        co = "Colorado",
        ct = "Connecticut",
        dc = "D.C.",
        de = "Delaware",
        fl = "Florida",
        ga = "Georgia",
        hi = "Hawaii",
        ia = "Iowa",
        id = "Idaho",
        il = "Illinois",
        in = "Indiana",
        ks = "Kansas",
        ky = "Kentucky",
        la = "Louisiana",
        ma = "Massachusettes",
        md = "Maryland",
        me = "Maine",
        mi = "Michigan",
        mn = "Minnesota",
        mo = "Missouri",
        ms = "Mississippi",
        mt = "Montana",
        nc = "North Carolina",
        nd = "North Dakota",
        ne = "Nebraska",
        nh = "New Hampshire",
        nj = "New Jersey",
        nm = "New Mexico",
        nv = "Nevada",
        ny = "New York",
        ok = "Oklahoma",
        oh = "Ohio",
        or = "Oregon",
        pa = "Pennsylvania",
        ri = "Rhode Island",
        sc = "South Carolina",
        sd = "South Dakota",
        tn = "Tennessee",
        tx = "Texas",
        ut = "Utah",
        va = "Virginia",
        vt = "Vermont",
        wa = "Washington",
        wi = "Wisconsin",
        wv = "West Virginia",
        wy = "Wyoming",

    }
